server:
  port: 8888

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
    gateway:
      routes:
        - id: governance-service
          uri: lb://GOVERNANCE-SERVICE
          predicates:
            - Path=/policies, /policies/**
        - id: audit-service
          uri: lb://AUDIT-SERVICE
          predicates:
            - Path=/audits, /audits/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    instances:
      governanceCircuitBreaker:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
      auditCircuitBreaker:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 2
  timelimiter:
    instances:
      governanceCircuitBreaker:
        timeoutDuration: 3s
      auditCircuitBreaker:
        timeoutDuration: 3s

